In [47]:
from transformers import pipeline

In [48]:
qa_pipeline = pipeline("question-answering")

No model was supplied, defaulted to distilbert-base-cased-distilled-squad and revision 626af31 (https://huggingface.co/distilbert-base-cased-distilled-squad).
Using a pipeline without specifying a model name and revision in production is not recommended.


In [49]:
context = """Bangladesh is still lagging behind competitors in the production of recycled yarn 
although the market for such yarn is swelling, especially in tune with new environmental laws being 
formulated by the European Union (EU). Recycled yarn is manufactured from worn-out or scrap textiles, 
furniture and clothing or other materials like plastic bottles. Though much of the recycling processes 
are patented, the basic concept involves creating pulp or fibres and turning those into yarn. 
Sometimes virgin cotton is also added to the mix. Use of apparel made from recycled yarn has been 
growing globally as consumers behaviour is changing centring the need for protecting the environment 
and slowing down climate change."""

In [50]:
#question= "How recycled yarn is manufactured?"
question = "What is the capital of Bangladesh?"

In [51]:
qa_pipeline(question = question, context = context)

{'score': 0.4294885993003845, 'start': 0, 'end': 10, 'answer': 'Bangladesh'}

In [52]:
from transformers import AutoTokenizer, AutoModelForQuestionAnswering

In [53]:
model_checkpoint = "distilbert-base-cased-distilled-squad"

In [54]:
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

In [55]:
model = AutoModelForQuestionAnswering.from_pretrained(model_checkpoint)

In [56]:
inputs = tokenizer(question, context, return_tensors = "pt")
outputs = model(**inputs)

In [57]:
start_logits = outputs.start_logits
end_logits = outputs.end_logits

In [58]:
print(start_logits.shape, end_logits.shape)

torch.Size([1, 143]) torch.Size([1, 143])


In [59]:
 long_context = """
Bangladesh is a country in South Asia, located in the delta of the Padma (Ganges) and Jamuna (Brahmaputra) rivers in the northeastern part of the Indian subcontinent. It is the eighth-most populous country in the world, with a population of over 169 million people. The official language of Bangladesh is Bengali, and the capital city is Dhaka.

Bangladesh is a relatively young country, having gained its independence from Pakistan in 1971. It is a developing country, with a GDP per capita of \$1,870 (PPP). However, Bangladesh has made significant progress in recent years, and is now considered to be a lower-middle-income country by the World Bank.

Bangladesh is a unique country in many ways. It is the world's largest riverine delta, and is home to a wide variety of flora and fauna. The Sundarbans, a mangrove forest on the southern coast, is the largest mangrove forest in the world and is home to the endangered royal Bengal tiger.

Bangladesh is also a diverse country, with a rich culture and history. The people of Bangladesh are predominantly Muslim, but there are also significant Hindu, Buddhist, and Christian minorities. The country is home to a number of UNESCO World Heritage Sites, including the ruins of the ancient city of Mahasthangarh and the Sundarbans mangrove forest.

Here are some interesting facts about Bangladesh:

Bangladesh is the world's eighth-most populous country.
Bangladesh is the most densely populated country in South Asia.
Bangladesh is the world's largest riverine delta.
Bangladesh is home to the Sundarbans, the largest mangrove forest in the world.
Bangladesh is a Muslim-majority country.
Bangladesh is a developing country, but has made significant progress in recent years.
Bangladesh is a diverse country, with a rich culture and history.
I hope this gives you a brief overview of Bangladesh. If you have any other questions, please let me know.
"""
qa_pipeline(question=question, context=long_context)

{'score': 0.9794791340827942, 'start': 339, 'end': 344, 'answer': 'Dhaka'}

In [60]:
import torch
sequence_ids = inputs.sequence_ids()
print(sequence_ids)
mask = [i !=1 for i in sequence_ids]
print(mask)

[None, 0, 0, 0, 0, 0, 0, 0, None, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None]
[True, True, True, True, True, True, True, True, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, Fa

In [61]:
print(mask[0])

True


In [62]:
mask[0] = False

In [63]:
mask = torch.tensor(mask)
mask

tensor([False,  True,  True,  True,  True,  True,  True,  True,  True, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, 

In [64]:
mask = torch.tensor(mask)[None]
mask

/tmp/ipykernel_32/4003029240.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mask = torch.tensor(mask)[None]


tensor([[False,  True,  True,  True,  True,  True,  True,  True,  True, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, F

In [65]:
start_logits[mask] = -10000
end_logits[mask] = -10000

In [66]:
print(start_logits.shape)
print(end_logits.shape)
print(start_logits)
print(end_logits)

torch.Size([1, 143])
torch.Size([1, 143])
tensor([[-8.0922e+00, -1.0000e+04, -1.0000e+04, -1.0000e+04, -1.0000e+04,
         -1.0000e+04, -1.0000e+04, -1.0000e+04, -1.0000e+04, -3.7279e+00,
         -1.0627e+01, -9.5806e+00, -7.9125e+00, -1.0255e+01, -9.2378e+00,
         -7.9050e+00, -1.0957e+01, -1.0459e+01, -1.0274e+01, -1.2139e+01,
         -7.9081e+00, -1.0998e+01, -1.1367e+01, -1.1012e+01, -9.1154e+00,
         -1.0154e+01, -1.2784e+01, -1.1848e+01, -9.8445e+00, -1.2533e+01,
         -1.1977e+01, -9.7134e+00, -1.2248e+01, -1.1579e+01, -1.1362e+01,
         -1.2287e+01, -1.2862e+01, -1.1116e+01, -1.0924e+01, -1.2517e+01,
         -1.2872e+01, -1.2336e+01, -1.2879e+01, -1.0002e+01, -8.5968e+00,
         -1.1503e+01, -1.2263e+01, -9.2598e+00, -1.2081e+01, -1.1264e+01,
         -9.6260e+00, -1.2300e+01, -1.2880e+01, -1.1594e+01, -1.3026e+01,
         -1.2809e+01, -1.2410e+01, -1.2673e+01, -1.1960e+01, -1.3074e+01,
         -1.3298e+01, -1.2923e+01, -1.2348e+01, -1.2290e+01, -1.3435e+

In [67]:
start_probabilities = torch.nn.functional.softmax(start_logits, dim=-1)[0]
end_probabilities = torch.nn.functional.softmax(end_logits, dim=-1)[0]
print(start_probabilities.shape)
print(end_probabilities.shape)

torch.Size([143])
torch.Size([143])


In [68]:
scores = start_probabilities[:, None] * end_probabilities[None, :]
print(scores.shape)
print(scores)

torch.Size([143, 143])
tensor([[6.3583e-04, 0.0000e+00, 0.0000e+00,  ..., 2.0231e-05, 1.4180e-05,
         0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        ...,
        [3.2791e-06, 0.0000e+00, 0.0000e+00,  ..., 1.0433e-07, 7.3131e-08,
         0.0000e+00],
        [4.0605e-06, 0.0000e+00, 0.0000e+00,  ..., 1.2919e-07, 9.0557e-08,
         0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00]], grad_fn=<MulBackward0>)


In [69]:
scores = torch.triu(scores)
print(scores.shape)
print(scores)

torch.Size([143, 143])
tensor([[6.3583e-04, 0.0000e+00, 0.0000e+00,  ..., 2.0231e-05, 1.4180e-05,
         0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        ...,
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 1.0433e-07, 7.3131e-08,
         0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 9.0557e-08,
         0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00]], grad_fn=<TriuBackward0>)


In [70]:
max_index = scores.argmax().item()
print(scores.argmax())
print(max_index)
print(scores.shape[1])
start_index = max_index // scores.shape[1]
print(start_index)
end_index = max_index % scores.shape[1]
print(end_index)
print(scores[start_index, end_index])

tensor(1296)
1296
143
9
9
tensor(0.4295, grad_fn=<SelectBackward0>)


In [71]:
inputs_with_offsets = tokenizer(question, context, return_offsets_mapping=True)
offsets = inputs_with_offsets["offset_mapping"]

start_char, _ = offsets[start_index]
_, end_char = offsets[end_index]
answer = context[start_char:end_char]
print(answer)

Bangladesh


In [72]:
result = {
    "answer": answer,
    "start": start_char,
    "end": end_char,
    "score": scores[start_index, end_index],
}
print(result)

{'answer': 'Bangladesh', 'start': 0, 'end': 10, 'score': tensor(0.4295, grad_fn=<SelectBackward0>)}


In [73]:
inputs = tokenizer(question, long_context)
print(len(inputs["input_ids"]))

410


In [74]:
tokenizer.model_max_length

512

In [75]:
inputs = tokenizer(question, long_context, max_length=384, truncation="only_second")
print(tokenizer.decode(inputs["input_ids"]))

[CLS] What is the capital of Bangladesh? [SEP] Bangladesh is a country in South Asia, located in the delta of the Padma ( Ganges ) and Jamuna ( Brahmaputra ) rivers in the northeastern part of the Indian subcontinent. It is the eighth - most populous country in the world, with a population of over 169 million people. The official language of Bangladesh is Bengali, and the capital city is Dhaka. Bangladesh is a relatively young country, having gained its independence from Pakistan in 1971. It is a developing country, with a GDP per capita of \ $ 1, 870 ( PPP ). However, Bangladesh has made significant progress in recent years, and is now considered to be a lower - middle - income country by the World Bank. Bangladesh is a unique country in many ways. It is the world's largest riverine delta, and is home to a wide variety of flora and fauna. The Sundarbans, a mangrove forest on the southern coast, is the largest mangrove forest in the world and is home to the endangered royal Bengal tige

In [76]:
len(inputs['input_ids'])

384

In [77]:
sentence = "This sentence is not too long but we are going to split it anyway."
inputs = tokenizer(
    sentence, truncation=True, return_overflowing_tokens=True, max_length=6, stride=2
)

for ids in inputs["input_ids"]:
    print(tokenizer.decode(ids))

[CLS] This sentence is not [SEP]
[CLS] is not too long [SEP]
[CLS] too long but we [SEP]
[CLS] but we are going [SEP]
[CLS] are going to split [SEP]
[CLS] to split it anyway [SEP]
[CLS] it anyway. [SEP]


In [78]:
sentences = [
    "This sentence is not too long but we are going to split it anyway.",
    "This sentence is shorter but will still get split.",
]
inputs = tokenizer(
    sentences, truncation=True, return_overflowing_tokens=True, max_length=6, stride=2
)
for ids in inputs["input_ids"]:
    print(tokenizer.decode(ids))
print(inputs["overflow_to_sample_mapping"])

[CLS] This sentence is not [SEP]
[CLS] is not too long [SEP]
[CLS] too long but we [SEP]
[CLS] but we are going [SEP]
[CLS] are going to split [SEP]
[CLS] to split it anyway [SEP]
[CLS] it anyway. [SEP]
[CLS] This sentence is shorter [SEP]
[CLS] is shorter but will [SEP]
[CLS] but will still get [SEP]
[CLS] still get split. [SEP]
[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1]


inputs = tokenizer(question, long_context, max_length=384, return_overflowing_tokens = True, stride = 4, truncation="only_second")

for ids in inputs['input_ids']:
    print(tokenizer.decode(inputs[ids]))

In [79]:
inputs = tokenizer(
    question,
    long_context,
    stride=128,
    max_length=384,
    padding="longest",
    truncation="only_second",
    return_overflowing_tokens=True,
    return_offsets_mapping=True,
)


In [80]:
print(type(inputs))
print(inputs.keys())
print(inputs.n_sequences)
#print(inputs.items)

<class 'transformers.tokenization_utils_base.BatchEncoding'>
dict_keys(['input_ids', 'attention_mask', 'offset_mapping', 'overflow_to_sample_mapping'])
2


In [81]:
_ = inputs.pop("overflow_to_sample_mapping")
offsets = inputs.pop("offset_mapping")

inputs = inputs.convert_to_tensors("pt")
print(inputs["input_ids"].shape)

torch.Size([2, 384])


In [82]:
outputs = model(**inputs)

start_logits = outputs.start_logits
end_logits = outputs.end_logits
print(start_logits.shape, end_logits.shape)

torch.Size([2, 384]) torch.Size([2, 384])


In [83]:
sequence_ids = inputs.sequence_ids()
# Mask everything apart from the tokens of the context
mask = [i != 1 for i in sequence_ids]
# Unmask the [CLS] token
mask[0] = False
# Mask all the [PAD] tokens
mask = torch.logical_or(torch.tensor(mask)[None], (inputs["attention_mask"] == 0))

start_logits[mask] = -10000
end_logits[mask] = -10000

In [88]:
start_probabilities = torch.nn.functional.softmax(start_logits, dim=-1)
end_probabilities = torch.nn.functional.softmax(end_logits, dim=-1)

In [89]:
candidates = []
for start_probs, end_probs in zip(start_probabilities, end_probabilities):
    scores = start_probs[:, None] * end_probs[None, :]
    idx = torch.triu(scores).argmax().item()

    start_idx = idx // scores.shape[1]
    end_idx = idx % scores.shape[1]
    score = scores[start_idx, end_idx].item()
    candidates.append((start_idx, end_idx, score))

print(candidates)

[(83, 83, 0.9794793725013733), (29, 32, 0.12783080339431763)]


In [90]:
for candidate, offset in zip(candidates, offsets):
    start_token, end_token, score = candidate
    start_char, _ = offset[start_token]
    _, end_char = offset[end_token]
    answer = long_context[start_char:end_char]
    result = {"answer": answer, "start": start_char, "end": end_char, "score": score}
    print(result)

{'answer': 'Dhaka', 'start': 339, 'end': 344, 'score': 0.9794793725013733}
{'answer': 'Mahasthangarh', 'start': 1248, 'end': 1261, 'score': 0.12783080339431763}
