In [245]:
#pip install transformers

In [246]:
import torch
from transformers import DistilBertModel,DistilBertTokenizer

In [247]:
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased-finetuned-sst-2-english')
model= DistilBertModel.from_pretrained('distilbert-base-uncased-finetuned-sst-2-english')

Some weights of the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing DistilBertModel: ['classifier.bias', 'pre_classifier.weight', 'pre_classifier.bias', 'classifier.weight']
- This IS expected if you are initializing DistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [248]:
sentences = "My name is Tarikul Islam Tamiti."

In [249]:
tokens = tokenizer.tokenize(sentences)

In [250]:
ids = tokenizer.convert_tokens_to_ids(tokens)

In [251]:
inputs = torch.tensor([ids])

In [252]:
outputs = model(inputs)

In [253]:
print(outputs.logits)

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ ❱ 1 print(outputs.logits)                                                                        │
│   2                                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'BaseModelOutput' object has no attribute 'logits'

In [ ]:
import torch
predictions = torch.nn.functional.softmax(outputs.logits, dim = -1)

In [261]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

sequence = [
    "I've been waiting for a HuggingFace course my whole life.",
    "I am a graduate of electrical and computer enginnering"
]

tokens = tokenizer.tokenize(sequence)
ids = tokenizer.convert_tokens_to_ids(tokens)
batched_ids = [ids]
input_ids = torch.tensor(batched_ids)
print("Input IDs:", input_ids)

output = model(input_ids)
print("Logits:", output.logits)
predictions = torch.nn.functional.softmax(output.logits, dim = -1)

Input IDs: tensor([[ 1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,  2607,
          2026,  2878,  2166,  1012,  1045,  2572,  1037,  4619,  1997,  5992,
          1998,  3274, 25540, 23111,  7999]])
Logits: tensor([[-1.0392,  1.2893]], grad_fn=<AddmmBackward0>)


In [262]:
print(predictions)

tensor([[0.0888, 0.9112]], grad_fn=<SoftmaxBackward0>)


In [ ]:
padding_id = 100 

In [265]:
seq1_ids = [[500,400,400,700]]
seq2_ids = [[373,20,7]]

In [263]:
batched_id = [
    [500, 400, 400, 700],
    [373,20,7,tokenizer.pad_token_id]
]

In [269]:
print(model(torch.tensor(seq1_ids)).logits)

tensor([[ 0.8902, -0.8531]], grad_fn=<AddmmBackward0>)


In [270]:
print(model(torch.tensor(seq2_ids)).logits)

tensor([[ 0.5752, -0.5355]], grad_fn=<AddmmBackward0>)


In [271]:
print(model(torch.tensor(batched_id)).logits)

tensor([[ 0.8902, -0.8531],
        [ 0.6690, -0.6281]], grad_fn=<AddmmBackward0>)


In [272]:
attention_mask = [
    [1,1,1,1],
    [1,1,1,0]
]

In [273]:
print(model(torch.tensor(batched_id), attention_mask = torch.tensor(attention_mask)).logits)

tensor([[ 0.8902, -0.8531],
        [ 0.5752, -0.5355]], grad_fn=<AddmmBackward0>)
